mariadb:
  configmap:
    name: config-mariadb-service-1-iobdbdqo4e
  secret:
    name: secret-mariadb-service-1-iobdbdqo4e
    username: test
    password: "Root1234!"
    root_password: "Root1234!"
    database: test
    dbhost: mariadb-service-1-iobdbdqo4e
    port: 3306
  statefulset:
    name: mariadb-service-1-iobdbdqo4e
    image:
      url: registry.turacocloud.com/turaco-common/mariadb:10.4.11
service:
  port:
    name: http
    l4_protocol: TCP
    port: 3306
    targetPort: 3306
  label: mariadb-service-1-iobdbdqo4e
  name: mariadb-service-1-iobdbdqo4e
  selector: mariadb-service-1-iobdbdqo4e
  type:
  - ClusterIP
  - NodePort
statefulset:
  name: mariadb-service-1-iobdbdqo4e
  spec:
    name: mariadb-service-1-iobdbdqo4e
    servicename: mariadb-service-1-iobdbdqo4e
  replicas: -@replicas@-
  container:
    name: mariadb-service-1-iobdbdqo4e
    port: 3306
  volume:
    name: pvc-mariadb-service-1-iobdbdqo4e
  resource:
    request:
      memory: -@requestMemory@-
      cpu: -@requestCpu@-
    limits:
      memory: -@limitsMemory@-
      cpu: -@limitsCpu@-
  hpa:
    name: hpa-mariadb-service-1-iobdbdqo4e
    minReplicas: -@minReplicas@-
    maxReplicas: -@maxReplicas@-
    cpu: -@cpuAutoScale@-
    memory: -@memAutoScale@-
namespace: -@namespace@-
secret:
  name: 
  registry:
    name: regsecret
    url: -@imageRepoName@-
    username: -@accessKey@-
    password: -@secretKey@-
    email: info@twolinecode.com
pvc:
  name: pvc-mariadb-service-1-iobdbdqo4e
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
